# Server Configuration
server:
  port: 9500

# Spring Configuration
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # MongoDB
  data:
    mongodb:
      uri: mongodb://admin:ELzy8UGzJ7ErGsEwZh6zvTZfjykxy7REqUezfaFEBp7ELawMTHpsgy8Nf@194.164.172.33:27018/n8n-restapi?authSource=admin
  # External Config Files
  config:
    import: classpath:config/config.yml

# Springdoc Configuration
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs